name: CI/CD Pipeline for Playwright (Java, TestNG, Allure, Logback)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (replace with your desired Java version)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Use the Java version your project requires
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      # Step 4: Build the project and run tests
      - name: Build and run tests with Maven
      # run only the target test runner that you need.
        run: mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testRunners/testig_regressions.xml

      # Step 5: Generate Allure report
      - name: Generate Allure report
        run: mvn allure:report

      # Step 6: Upload Allure report as an artifact
      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin